export const genericNames = [
  "Elvandar",
  "Nimrodel",
  "Arandor",
  "Faelivrin",
  "Eldamar",
  "Caelondia",
  "Thalassia",
  "Galadrielle",
  "Earendil",
  "Celeborn",
  "Aurelian",
  "Alatar",
  "Eruanna",
  "Lorieniel",
  "Elrosiel",
  "Calenloth",
  "Eolande",
  "Vardaessa",
  "Thranduil",
  "Eowynne",
  "Amrothos",
  "Glorfindel",
  "Luthien",
  "Elessar",
  "Galathil",
  "Ardalambion",
  "Fingolfin",
  "Eolair",
  "Arien",
  "Aranthir",
  "Arodion",
  "Cirdan",
  "Finrod",
  "Gwindor",
  "Ingwion",
  "Melian",
  "Mithrandir",
  "Mannix",
  "Radagast",
  "Saruman",
  "Ulmo",
];

export function getRandomCharacterName(): string {
  let nameList = genericNames;
  return nameList[Math.floor(Math.random() * nameList.length)];
}
